-- Grunter beta Supabase setup
-- Paste this whole file into Supabase SQL Editor and click Run.
--
-- This is intentionally simple for a small closed beta.
-- It lets anyone with the app link read and post Grunter data.
-- For a stricter private version later, add Supabase Auth or an invite system.

create table if not exists public.users (
  id uuid primary key,
  display_name text not null default 'Guest',
  avatar text not null default ':)',
  created_at timestamptz not null default now()
);

create table if not exists public.grunts (
  id uuid primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null default 'Untitled Grunt',
  audio_path text not null,
  duration_ms integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  grunt_id uuid not null references public.grunts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  body text not null check (length(body) <= 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  grunt_id uuid not null references public.grunts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  unique (grunt_id, user_id, emoji)
);

create table if not exists public.battles (
  id bigint generated by default as identity primary key,
  grunt_a_id uuid not null references public.grunts(id) on delete cascade,
  grunt_b_id uuid not null references public.grunts(id) on delete cascade,
  status text not null default 'live' check (status in ('live', 'closed')),
  ends_at timestamptz not null default (now() + interval '24 hours'),
  winner_grunt_id uuid references public.grunts(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.battle_votes (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  voted_grunt_id uuid not null references public.grunts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (battle_id, user_id)
);

create index if not exists grunts_created_at_idx on public.grunts(created_at desc);
create index if not exists comments_grunt_id_created_at_idx on public.comments(grunt_id, created_at);
create index if not exists reactions_grunt_id_idx on public.reactions(grunt_id);
create index if not exists battles_created_at_idx on public.battles(created_at desc);
create index if not exists battle_votes_battle_id_idx on public.battle_votes(battle_id);

alter table public.users enable row level security;
alter table public.grunts enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;
alter table public.battles enable row level security;
alter table public.battle_votes enable row level security;

drop policy if exists "grunter users read" on public.users;
drop policy if exists "grunter users write" on public.users;
drop policy if exists "grunter grunts read" on public.grunts;
drop policy if exists "grunter grunts write" on public.grunts;
drop policy if exists "grunter comments read" on public.comments;
drop policy if exists "grunter comments write" on public.comments;
drop policy if exists "grunter reactions read" on public.reactions;
drop policy if exists "grunter reactions write" on public.reactions;
drop policy if exists "grunter battles read" on public.battles;
drop policy if exists "grunter battles write" on public.battles;
drop policy if exists "grunter battle votes read" on public.battle_votes;
drop policy if exists "grunter battle votes write" on public.battle_votes;

create policy "grunter users read" on public.users
for select to anon using (true);

create policy "grunter users write" on public.users
for all to anon using (true) with check (true);

create policy "grunter grunts read" on public.grunts
for select to anon using (true);

create policy "grunter grunts write" on public.grunts
for insert to anon with check (true);

create policy "grunter comments read" on public.comments
for select to anon using (true);

create policy "grunter comments write" on public.comments
for insert to anon with check (true);

create policy "grunter reactions read" on public.reactions
for select to anon using (true);

create policy "grunter reactions write" on public.reactions
for insert to anon with check (true);

create policy "grunter battles read" on public.battles
for select to anon using (true);

create policy "grunter battles write" on public.battles
for all to anon using (true) with check (true);

create policy "grunter battle votes read" on public.battle_votes
for select to anon using (true);

create policy "grunter battle votes write" on public.battle_votes
for insert to anon with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'grunts',
  'grunts',
  true,
  10485760,
  array['audio/webm', 'audio/mp4', 'audio/wav', 'audio/mpeg', 'audio/ogg']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "grunter audio read" on storage.objects;
drop policy if exists "grunter audio upload" on storage.objects;
drop policy if exists "grunter audio update" on storage.objects;

create policy "grunter audio read" on storage.objects
for select to anon using (bucket_id = 'grunts');

create policy "grunter audio upload" on storage.objects
for insert to anon with check (bucket_id = 'grunts');

create policy "grunter audio update" on storage.objects
for update to anon using (bucket_id = 'grunts') with check (bucket_id = 'grunts');

alter table public.grunts replica identity full;
alter table public.comments replica identity full;
alter table public.reactions replica identity full;
alter table public.battles replica identity full;
alter table public.battle_votes replica identity full;

do $$
declare
  rt_table text;
begin
  foreach rt_table in array array['grunts', 'comments', 'reactions', 'battles', 'battle_votes']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = rt_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', rt_table);
    end if;
  end loop;
end $$;
